#!/usr/bin/bash
echo "Calculadora Básica para NÚMEROS INTEIROS"

read -p "Informe um número: " numero1
read -p "Informe outro número: " numero2

soma=$(($numero1 + $numero2))
subtracao=$(($numero1 - $numero2))
multiplicacao=$(($numero1 * $numero2))
divisao=$(($numero1/$numero2))

echo "$numero1 + $numero2 = $soma"
echo "$numero1 - $numero2 = $subtracao"
echo "$numero1 x $numero2 = $multiplicacao"
echo "$numero1 / $numero2 = $divisao"
